# Generated by Django 5.2.9 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile_telegram_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_demo_user",
            field=models.BooleanField(default=False),
        ),
    ]
