# Generated by Django 5.2.9 on 2026-02-10 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('thread_id', models.CharField(db_index=True, max_length=255)),
                ('received_at', models.DateTimeField(db_index=True)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('snippet', models.TextField(blank=True)),
                ('detected_type', models.CharField(choices=[('unknown', 'Unknown'), ('response', 'Response'), ('rejection', 'Rejection'), ('invite', 'Invite'), ('auto_ack', 'Auto acknowledgment'), ('noise', 'Noise')], db_index=True, default='unknown', max_length=32)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('is_user_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'received_at'], name='gmail_stats_user_id_983e10_idx'), models.Index(fields=['user', 'detected_type'], name='gmail_stats_user_id_16547e_idx')],
            },
        ),
    ]
