# Generated by Django 5.2.9 on 2025-12-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_jobapplication_applied_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='recruiter_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
