# Generated by Django 5.2.9 on 2026-03-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Job application', 'verbose_name_plural': 'Job applications'},
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(blank=True, choices=[('stepstone', 'StepStone'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('xing', 'Xing'), ('glassdoor', 'Glassdoor'), ('arbeitsagentur', 'Arbeitsagentur'), ('company', 'Company website'), ('recruiter', 'Recruiter'), ('referral', 'Referral'), ('other', 'Other')], max_length=50, verbose_name='Source'),
        ),
    ]
