# Generated by Django 5.2.9 on 2025-12-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewevent',
            name='ends_at',
        ),
    ]
