# Generated by Django 5.2.9 on 2025-12-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_remove_interviewevent_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewevent',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('done', 'Done'), ('canceled', 'Canceled')], default='scheduled', max_length=16),
        ),
    ]
