# Generated by Django 5.2.9 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram_bot", "0005_rename_deploy_request_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramdeployrequest",
            name="target_description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
